services:
  postgres:
    image: urso-db:16
    container_name: urso-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5431:5432"

    volumes:
      - urso-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  urso-db-data:

